### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by kevin700523** [larvacloud/laravel-skeleton#1]
`php artisan migrate --seed`

`Seeding: AdminTablesSeeder
Illuminate\Database\QueryException`

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'settings-user' for key 'admin_permissions.admin_permissions_slug_unique' (SQL: insert into `admin_permissions` (`created_at`, `http_method`, `http_path`, `id`, `name`, `order`, `parent_id`, `slug`) values (2020-06-22 02:41:52, , , 9, 用户管理, 1, 0, user-management), (2020-06-22 02:41:52, , /user/settings/basic, 10, 用户设置, 2, 9, settings-user), (2020-06-22 02:41:52, , user/clients, 11, OAuth客户端管理, 3, 9, settings-user))

**Comment by larvacent** [comment]
修好了
