### ISSUE TITLE
短信队列报错

### ISSUE THREAD

**Issue by Tsukison** [larvacloud/laravel-skeleton#5]
日志里面：local.ERROR: Target class [sms] does not exist. 
`public function handle()
    {
        try {
            app('sms')->send($this->mobile, $this->message);//这什么问题 
        } catch (NoGatewayAvailableException $exception) {
            foreach ($exception->getExceptions() as $e) {
                Log::error($e);
            }
        } catch (\Exception $exception) {
            Log::error($exception->getMessage());
        }
    }`

**Comment by larvacent** [comment]
你需要配置短信才能用的
